name: Deploy Penguin API to the Duplicated Environment by terraform

on:
  push:
    branches: [ "main" ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_path: ${{ steps.build.outputs.IMAGE_PATH }}
      image_digest: ${{ steps.build.outputs.IMAGE_DIGEST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push
        id: build
        run: |
          IMAGE="asia-northeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/penguin-api/penguin-api:${{ github.sha }}"
          
          gcloud builds submit \
            --tag $IMAGE \
            --gcs-source-staging-dir="gs://ml-test002-build/source" \
            --quiet .

          DIGEST=$(gcloud container images describe $IMAGE --format='get(image_summary.digest)')
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_OUTPUT
          echo "IMAGE_PATH=$IMAGE" >> $GITHUB_OUTPUT

  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Deploy to Cloud Run (Dev)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: 'asia-northeast1'
          image: "${{ needs.build-and-push.outputs.image_path }}@${{ needs.build-and-push.outputs.image_digest }}"